require("neco.plugins-setup")
require("neco.core.options")
require("neco.core.keymaps")
require("neco.core.colorscheme")
require("neco.plugins.comment")
require("neco.plugins.nvim-tree")
require("neco.plugins.lualine")
require("neco.plugins.telescope")
require("neco.plugins.nvim-cmp")
require("neco.plugins.lsp.lspconfig")
require("neco.plugins.lsp.mason")
require("neco.plugins.lsp.null-ls")
require("neco.plugins.lsp.lspsaga")
-- require("neco.plugins.barbar")
require("neco.plugins.gitsigns")
require("neco.plugins.treesitter")
-- require("neco.plugins.autopairs")
require("neco.plugins.toggleterm")
require("neco.plugins.fterm")
require("neco.core.command")
